---
title: "Owner Analysis"
author: "Collin J. Closek"
date: "2023-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Packages

```{r}

library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)

```

## Pull in data

```{r, message=FALSE, warning=FALSE}
lobster_abundance <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-sbc.77.8&entityid=f32823fba432f58f66c06b589b7efac6")
lobster_trap <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-sbc.77.8&entityid=66dd61c75bda17c23a3bce458c56ed84")

#Option2
#lobster_trap <- read_csv(../data/FILENAME) #.. moves into the higher level out of the analysis folder to read see the data folder
```

## Explore data
```{r}
glimpse(lobster_abundance)
unique(lobster_abundance$SITE)
glimpse(lobster_trap)
```

# Create data subsets 

Convert missing values using mutate() and na_if(), apply filters with conditions
```{r}
lobster_abundance <- lobster_abundance %>% 
  mutate(SIZE_MM = na_if(SIZE_MM, -99999)) 

not_napl <- lobster_abundance %>% 
  filter(SITE!="NAPL")

arroyo_70 <- lobster_abundance %>% 
  filter(SITE=="AQUE" | SIZE_MM > 70) #& and && indicate logical AND and | and || indicate logical OR
```

# Exercise: Data Visualization

```{r}
abundance_plot <- lobster_abundance %>% 
  ggplot(aes(x = SIZE_MM), fill=)+
    geom_histogram()+
    facet_wrap(~SITE)+
  ##theme
    theme(
      axis.line = element_blank(),
      plot.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank())+
  ##labels
  ggtitle("Lobsters by size and region")+
  xlab("Size (mm)") + ylab("Count")
ggsave("figs/abundance_plot.png",abundance_plot)



```

